### ISSUE TITLE
Delete carts

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/tbcleaner#2]
Shops tend to collect empty carts over time. Each time a customer clicks on the cart, a cart gets created, even if there's nothing inside. As these empty carts have no purpose, delete them after some time. For example, after the cookie expiration time.

See https://forum.thirtybees.com/topic/2196/sort-cart-controller-by-total-amount

Alternative: don't even create such carts.

Also, look up which carts remain reachable after some time. A cart without related address and without related cookie in the user's browser is probably unreachable, just wasting space (database, back office list rows).

**Comment by Dh42** [comment]
I am moving this to the cleaner module, it seems a logical place to extend this. I am also doing this to test out the move feature that is in beta.

**Comment by Traumflug** [comment]
Running the cleaner module in a shop already set up deletes all products, categories, orders and whatever. This appears to be a better place for maintenance tasks like deleting empty carts: https://github.com/thirtybees/thirtybees/blob/1.0.x/classes/ShopMaintenance.php

**Comment by getdatakick** [comment]
Deleting empty carts should indeed be responsibility of core
